static_resources:
  listeners:
    - name: staticreply
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8099
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/ok"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "example body from behind Envoy!\n"
                        - match:
                            prefix: "/fail"
                          direct_response:
                            status: 503

                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router  
    - name: main
      address:
          socket_address:
            address: 0.0.0.0
            port_value: 8000
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            codec_type: AUTO
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: upstream
                domains:
                - "*"
                routes:
                - match:
                    prefix: "/httpbin"
                  route:
                    cluster: httpbin                
                - match:
                    prefix: "/"
                  route:
                    cluster: upstream-service

            http_filters:
            # - name: envoy.filters.http.ext_authz
            #   typed_config:
            #     "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            #     grpc_service:
            #       envoy_grpc:
            #         cluster_name: ext_authz-grpc-service
            #       timeout: 0.250s
            #     transport_api_version: V3
                
            - name: envoy.filters.http.router

  clusters:
  - name: upstream-service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: upstream-service
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8099
  - name: httpbin
    connect_timeout: 5000s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: httpbin
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: httpbin.org
                    port_value: 80
  # - name: upstream-service
  #   type: STRICT_DNS
  #   lb_policy: ROUND_ROBIN
  #   load_assignment:
  #     cluster_name: upstream-service
  #     endpoints:
  #     - lb_endpoints:
  #       - endpoint:
  #           address:
  #             socket_address:
  #               address: upstream-service
  #               port_value: 8080

  - name: ext_authz-grpc-service
    type: STATIC
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: ext_authz-grpc-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9001
        - endpoint:
            address:
              socket_address:
                address: 9.134.189.148
                port_value: 9001                
